### ISSUE TITLE
Reputation doesn't update to latest

### ISSUE THREAD

**Issue by Demonicka** [DJScias/Experiencer2#10] opened 2024-08-30 22:24 UTC
## Expected Behavior
Reputation is set to update to most recent gained reputation

## Actual Behavior
Reputation does not update to most recent gained reputation

## Steps to Reproduce the Problem

  1.Set bar to show reputation. No reputations are inactive.
  2.Set bar to show current & max next section clicked all (show gain/auto add/auto switch bar to last gained)
  3.Bar remains same, in order to change from no tracked reputation, it must be set manually. Gains are made from multiple reputations, only the manually set reputation shows. If none is manually set, then the bar remains empty.

**Comment by DJScias** [comment] 2024-09-03 02:11
Hello there,

I have followed your steps and I can reproduce an error.
However even with this error, my bar still changes all the same.

I'll push a fix soon for this, but I do wonder if this is the same issue as you're having then.
If possible, could you check on BugSack regarding the error and post it here?

**Comment by Demonicka** [comment] 2024-09-03 02:13
What's Bugsack?

**Comment by DJScias** [comment] 2024-09-03 02:15
> What's Bugsack?

Basically you download the following addons, and when an error is found it will output it to a window.
https://www.curseforge.com/wow/addons/bug-grabber
https://www.curseforge.com/wow/addons/bugsack

With the output of that window, I can then have a sort of an idea what caused the issue you're having (and if I caught the right one in my latest commit).

**Comment by JBabbb** [comment] 2024-09-03 16:27
Hello, would like to confirm I'm running into the same issue!

The reputations are not changing automatically, even with 'auto switch bar to last gained reputation' ticked.
Having to manually select the reputation in the reputations panel to track one at a time.

Thanks for the awesome addon :)

**Comment by Demonicka** [comment] 2024-09-03 20:36
I didn't see any experiencer error in Bugsack.

**Comment by DJScias** [comment] 2024-09-05 21:19
> Hello, would like to confirm I'm running into the same issue!
> 
> The reputations are not changing automatically, even with 'auto switch bar to last gained reputation' ticked. Having to manually select the reputation in the reputations panel to track one at a time.
> 
> Thanks for the awesome addon :)

Hey @JBabbb,

Quick question. Is this happening when you start from not tracking any reputation?
![image](https://github.com/user-attachments/assets/e5bd4556-5d09-4a7a-9682-0f7f84ab7278)

Or does it happen all the time?

**Comment by DJScias** [comment] 2024-09-05 21:34
Hey @JBabbb and @Demonicka.

I've just released 6.1.7 which fixes the error on my end (where I'm hoping it's the same one as you two are having).
Could you two please grab the latest update (CurseForge/Wago/WoWInterface) and let me know if you still have the issue?

If not, please do let me know!

**Comment by Demonicka** [comment] 2024-09-05 23:30
Sorry, but there was no change. I'd had it set to Assembly of the Deeps, and it was set to auto switch to latest gained. When I looted a reputation item that gave 150 reputation to Council of Dornogal the bar did not change.

**Comment by DJScias** [comment] 2024-09-06 00:04
I think I know what's going on and it's unfortunately not something I can fix soon/ever.
Back in the previous expansion, gaining reputation would be called out in your chat log.

The quests in The War Within that give you reputation don't have it shown in the chat log.
This is the primary way Experiencer grabs the "gains" basically. So it being done 'in silence' makes it unable to see it.

I'll see if I can find a way to make it still work, but this might be a feature that won't work in The War Within specifically as it stands.

**Comment by DJScias** [comment] 2024-09-06 00:13
Nevermind, I think I have figured out what might be going on. Posting this here for memory:

```
Your Warband's reputation with Hallowfall Arathi increased by 150. 
```

**Comment by DJScias** [comment] 2024-09-06 00:30
Managed to fix it in my local build.
![image](https://github.com/user-attachments/assets/5995b5e0-5333-4b14-bf6d-e98c3d1295c8)
![image](https://github.com/user-attachments/assets/8e2d7fbf-fbbb-49ca-acd8-a2cd7e19b1ec)

I will upload these fixes soon and push 6.1.8

**Comment by DJScias** [comment] 2024-09-06 00:39
@Demonicka and @JBabbb.

6.1.8 just got pushed to (CurseForge/Wago/WoWInterface.
I think I got it this time, as auto-switching (and counting gains) now properly works for the TWW reputations.

Please do keep me updated in this thread, and thank you two again for helping me narrow down the issue!

**Comment by JBabbb** [comment] 2024-09-06 08:57
Hi @DJScias,

Sorry for not responding earlier! I'm on the Australian timezone, so I've been at work all day.
Unfortunately, the auto tracking is still not working for me. 

This includes both when tracking absolutely nothing in the reputation panel, and when tracking a random reputation. Neither scenario causes the auto-switch to work as intended. Again, the only things selected in my experiencer reputation settings is 'show current & max reputation' and 'auto switch bar to last gained reputation' - everything else is unticked.

Kind regards :)

**Comment by DJScias** [comment] 2024-09-06 17:12
> Hi @DJScias,
> 
> Sorry for not responding earlier! I'm on the Australian timezone, so I've been at work all day. Unfortunately, the auto tracking is still not working for me.
> 
> This includes both when tracking absolutely nothing in the reputation panel, and when tracking a random reputation. Neither scenario causes the auto-switch to work as intended. Again, the only things selected in my experiencer reputation settings is 'show current & max reputation' and 'auto switch bar to last gained reputation' - everything else is unticked.
> 
> Kind regards :)

Hey there,

Could you hover over "Experiencer Options" (the title in the options list) and tell me what version it says there?

I unfortunately can't reproduce this at all, everything works fine on my end.

A few questions:
Could you perhaps get me any steps that reproduce it 100% of the time for you?
Which reputation are you trying to auto-switch to?
Where/how are you trying to make the switch happen?
Perhaps a video of you trying to make the switch happen?

As it's all working for me now, I wouldn't really know where to start debugging this issue of yours without more details.

**Comment by DJScias** [comment] 2024-09-06 21:24
Did a few more tests right now and can confirm I've not been having issues.

Before anything:
![image](https://github.com/user-attachments/assets/f8993fb1-98e5-45d0-a702-0dd471d5bdaa)

Finishing a quest:
![image](https://github.com/user-attachments/assets/a6ed38d8-2309-4eca-886d-b93091055aed)

After quest, gain rep + auto-switch:
![image](https://github.com/user-attachments/assets/b6f173e3-b098-45ea-b5d4-78c5c416111e)
![image](https://github.com/user-attachments/assets/956112f9-573c-425f-91dc-6d1e4b63e4e0)

My reputation settings on 6.1.8
![image](https://github.com/user-attachments/assets/ccb40266-8f82-4439-a4ad-99d500cdd53d)

**Comment by JBabbb** [comment] 2024-09-07 14:08
Hi @DJScias,

I can confirm 6.1.8 has fixed this issue, AND I have narrowed down the issue for it not auto-tracking.
The 'auto add to recent reputations list' must be ticked alongside the 'auto switch bar to last gained reputation' for it to work, if it is only the latter setting ticked, it still doesn't auto update for me.

I think adding some information into the tooltip for 'auto add to recent reptuations list' would be useful for other users. Maybe something like 'This setting needs to be ticked for the auto switch function to work as intended'.

Sorry for the bother... :')

**Comment by DJScias** [comment] 2024-09-07 15:01
> Hi @DJScias,
> 
> I can confirm 6.1.8 has fixed this issue, AND I have narrowed down the issue for it not auto-tracking. The 'auto add to recent reputations list' must be ticked alongside the 'auto switch bar to last gained reputation' for it to work, if it is only the latter setting ticked, it still doesn't auto update for me.
> 
> I think adding some information into the tooltip for 'auto add to recent reptuations list' would be useful for other users. Maybe something like 'This setting needs to be ticked for the auto switch function to work as intended'.
> 
> Sorry for the bother... :')

Hey there!

No bother at all, this is actually good info.
I hadn't thought of the two settings being intricately linked together.

I'll see to getting a way to have that be reflected in the menu somehow soon!

Thanks again for all the checking for me.

**Comment by DJScias** [comment] 2024-09-07 21:01
Hello there.

6.2.0 has just been released and it should fix this behavior.

Both options can now be toggled independently from one another, so you can have auto-switch on without auto-add being on and vice versa. However obviously auto-switching to something will auto-add that reputation to the recent list.

I'll keep the issue open for a bit so you can check 6.2.0 to see if it all works as it should now.

Thank you both for helping me get to the bottom of this!

**Comment by JBabbb** [comment] 2024-09-08 09:11
Thank you for your work @DJScias.

All works perfectly now :)

**Comment by Demonicka** [comment] 2024-09-08 20:52
Seems to be working great! Thanks for the fixes <3

**Comment by Demonicka** [comment] 2024-09-08 23:44
One thing I've noticed just now on one of my alts, that even though I'm revered with my guild, whenever I get guild rep the bar changes but it says Guild (Neutral) 1/3000

**Comment by DJScias** [comment] 2024-09-09 15:06
> One thing I've noticed just now on one of my alts, that even though I'm revered with my guild, whenever I get guild rep the bar changes but it says Guild (Neutral) 0/3000. I can manually switch it to show guild reputation, but the next time I get reputation it will say Neutral again. Didn't notice it on my main yet but maybe it's because she's exalted with her guild.

Hey there.

Not entirely sure what would cause this.
I'll investigate and see if I can reproduce.

**Comment by DJScias** [comment] 2024-09-10 14:44
Hello there,

Quickly pulled that last issue into another issue, as this one is strictly fixed now.
Just to keep things tidy and organized.

**Closed by DJScias** 2024-09-10 14:44 UTC
Labels: bug, help wanted
